$(function(){
    $("#signOut").on('click',function(){
        $.ajax({
            url:'logout.php?status=logOut',
            success:function(rep){
                if(rep==1){
                    location.href='index.html'
                }
            }
        })
    });
})